### ISSUE TITLE
[Suggestion] Limit the amount of concurrently downloaded files

### ISSUE THREAD

**Issue by SXZ1** [marklieberman/downloadstar#19]
Hello!
As the title says, it would be great to add an ability to limit the amount of concurrently downloaded files. Right now Download Star imports all selected files to the built-in Firefox download manager at once. That's not very convenient with big number of selected files because Firefox starts to download them all at the same time.

Thank you very much!

**Comment by marklieberman** [comment]
I don't want to go and implement a whole download manager in this addon. If DtA Lite ever releases, I'm pretty sure everyone will switch to that. Possibly, I can add the downloads and then pause them and limit it to 2-4 concurrent downloads.

**Comment by OkanEsen** [comment]
I actually think about this the same way as @marklieberman does. I use this addon because it's quite lightweight and doesn't feel packed with huge features making it cumbersome to use. 

For me personally the files to download range between 5-10 maximum and the file sizes are between 1-10MB so downloading them all at once isn't that huge for the network to deal.
