### ISSUE TITLE
download links without extension

### ISSUE THREAD

**Issue by GianniGi** [marklieberman/downloadstar#33]
For what I've seen, this addon works only when the url - file that you need to download has an extension at the end of the link. 

If the link to be downloaded is something like ..../download123/ the downloader doesn't work

In this specific case the page required a login.

**Comment by bup4gr** [comment]
Same problem shown here https://github.com/marklieberman/downloadstar/issues/27 (second comment).
Probably automatic naming/extension can solve the problem.

**Comment by GianniGi** [comment]
When you download the files, instead of getting the correct filenames, you simpy find in your download directory many files called "download(number)", without file extension or anything. This is really annoying, since you have to guess the extension of each file. After that, you still have no way to retry the download of the failed files.

**Comment by marklieberman** [comment]
@GianniGi In you example HTML there are no filenames, so there is no "correct" filename. Probably, the server uses the Content-Disposition header to specify a filename. DownloadStar cannot see this header because the web extensions downloads API is missing a lot of features.

The closest thing to a solution would be to collect the text content of the link and allow you to use that as the filename instead.
