### ISSUE TITLE
Filters default to Images.

### ISSUE THREAD

**Issue by ilpooh** [marklieberman/downloadstar#71]
After any download the control popup window resets to "Images" checkbox. It makes no difference if I choose "Immediately save changes to controls in the popup" from "Options".

I am not sure when this problem started but it wasn't there a few months ago. For my purposes I only need regular expression fast filter and this addon has done this perfectly until now.

**Comment by Quaroon** [comment]
Same experience here. It also seems to have started a few months ago. I also tried reinstalling the addon fresh but get the same result.  Using firefox on Linux if that makes any difference.

**Comment by MegaScience** [comment]
I've had this issue as well. It happened around the time I had some computer trouble and chalked it up to something getting stored incorrectly with that, but if the problem is affecting others I'd be more inclined to believe it is universal.

**Comment by dd333** [comment]
Same here.  Was going to try remove' add back, but see that has been tried.   The "Immediately save changes to controls in the popup" in the options is checked.

**Comment by atlanto** [comment]
This problem is due to API incompatibility(?).
browser.storage.local.set() seems to make vm.filters empty when saving, so filters settings becomes default everytime.
No such problem with extensions.webextensions.ExtensionStorageIDB.enabled=false.(Caution:do not modify this pref, otherwise you will lose extensions settings)
To avoid this problem, omit get/set function in filters. For example,
```
function saveControls () {
  let filters = {};
  for (let key in vm.filters) {
    filters[key] = vm.filters[key];
  }
  return browser.storage.local.set({
    controls: vm.controls,
    filters: filters
  });
}
```
(though not verified since I don't have develop environment)
